(column-number-mode t)
(setq inferior-lisp-buffer "*inferior-lisp*")
(setq inhibit-startup-screen t)
(setq read-file-name-completion-ignore-case t)
(setq-default indent-tabs-mode nil)
(tool-bar-mode 0)

(setq auto-save-default nil)
(setq make-backup-files nil)

(show-paren-mode t)
(setq show-paren-style 'expression)

(add-to-list 'load-path "~/.emacs.d/clojure-mode")
(require 'clojure-mode)
(setq inferior-lisp-program "/usr/local/bin/lein repl")

(add-to-list 'load-path "~/.emacs.d/color-theme")
(require 'color-theme)
(color-theme-charcoal-black)

(add-to-list 'load-path "~/.emacs.d/paredit")
(require 'paredit)
(defun turn-on-paredit ()
  (define-key paredit-mode-map "{" 'paredit-open-curly)
  (define-key paredit-mode-map "}" 'paredit-close-curly)
  (modify-syntax-entry ?\{ "(}")
  (modify-syntax-entry ?\} "){")
  (modify-syntax-entry ?\[ "(]")
  (modify-syntax-entry ?\] ")[")
  (paredit-mode 1))
(add-hook 'clojure-mode-hook 'turn-on-paredit)
(add-hook 'emacs-lisp-mode-hook 'turn-on-paredit)
(add-hook 'inferior-lisp-mode-hook 'turn-on-paredit)
(add-hook 'lisp-interaction-mode-hook 'turn-on-paredit)
